{
 "title": "Wireguard",
 "description": "Metrics for Wireguard VPN",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Connected Clients (SI)",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(wireguard_received_bytes_total[$__rate_interval])",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate( wireguard_received_bytes_total[$__rate_interval])",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Send Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(wireguard_sent_bytes_total[$__rate_interval])",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Latest Handshakes (Seconds)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(wireguard_latest_handshake_seconds[$__rate_interval])",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  }
 ]
}