"ansible_bucket_name": "wireguard-configs-2ab6d6d6"
"server_endpoint": "63.178.158.49"
"wireguard_clients":
- "client_ip": "10.66.66.2"
  "client_private_key": "aLUlWd63rsbjKrRzFyjJterBGxQ/rKYK3+J38znBO3c="
  "client_public_key": "YqMA/PeLPaYBuXybO0mEfOHU34oFtoUDDV0nlIAHamw="
  "name": "ayoub"
