- name: Install and Configure WireGuard on WireGuard EC2
  hosts: wireguard
  vars_files:
    - /home/ubuntu/ansible/var.yml
  become: yes

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install WireGuard and dependencies
      apt:
        name:
          - wireguard
          - wireguard-tools
        state: present

    - name: Ensure /etc/wireguard directory exists
      file:
        path: /etc/wireguard
        state: directory
        mode: '0700'

    # ─── Always override any existing key ────────────────────────────────────────
    - name: Remove any existing server private key
      file:
        path: /etc/wireguard/privatekey
        state: absent

    - name: Generate new WireGuard server private key
      command: wg genkey
      register: wg_private_key

    - name: Save the new private key to file
      copy:
        content: "{{ wg_private_key.stdout }}"
        dest: /etc/wireguard/privatekey
        mode: '0600'
    # ─────────────────────────────────────────────────────────────────────────────
    - name: Render WireGuard config for each client
      template:
        src: templates/client.conf.j2
        dest: "/home/ubuntu/ansible/clients/{{ item.name }}.conf"
      loop: "{{ wireguard_clients }}"
      vars:
        server_endpoint: "{{ server_endpoint }}"
    - name: Read existing private key
      slurp:
        src: /etc/wireguard/privatekey
      register: existing_private_key

    - name: Decode private key
      set_fact:
        wireguard_private_key: "{{ existing_private_key.content | b64decode }}"

    - name: Generate WireGuard public key
      shell: echo "{{ wireguard_private_key }}" | wg pubkey
      register: wg_public_key
      changed_when: false

    - name: Create WireGuard configuration file using template
      template:
        src: wg0.conf.j2
        dest: /etc/wireguard/wg0.conf
        mode: '0600'

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    - name: Start and enable WireGuard service
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started

    - name: Delete wrong DHCP injected route for VPN client
      command: ip route del 10.0.0.2
      ignore_errors: yes
