name: Manual Terraform Destroy (in terra directory)

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type YES to confirm you want to destroy all infrastructure"
        required: true

permissions:
  contents: read

jobs:
  destroy:
    name: Terraform Destroy
    if: ${{ github.event.inputs.confirm_destroy == 'YES' }}
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - name: Decode CLIENTS secret and write to tfvars file
        run: |
          echo "${{ secrets.CLIENTS }}" | base64 -d > terra/clients.auto.tfvars

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: terra

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
        working-directory: terra

